### ISSUE TITLE
输入账号密码登入失败

### ISSUE THREAD

**Issue by 918975709** [PieceOfFall/-#1]
输入管理员账号密码登入失败，自己注册的一直收不到验证码，请问大概是什么原因呢，数据库没有配置好吗

**Comment by PieceOfFall** [comment]
后端启动了吗，启动了的话看看有没有报错信息

**Comment by PieceOfFall** [comment]
如果是连接数据库问题，请看[README中的常见问题](https://github.com/PieceOfFall/BookManage#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by 918975709** [comment]
这个我看了哒

**Comment by PieceOfFall** [comment]
所以有报错信息吗，有的话截图看看

**Comment by 918975709** [comment]
Failed to load resource: net::ERR CONNECTION REFUSED


那个图片我不会发

**Comment by PieceOfFall** [comment]
直接复制粘贴下来吧，报错信息

**Comment by 918975709** [comment]
#`POST` http://127.0.0.1:8833/api/validateMail net::ERR_CONNECTION_REFUSED

Uncaught (in promise) Error: Network Errorat createError
 (createError.is?2d83:16:1)at XLHttpRequest.handleError (xhr.js?b50d:117:1)

**Comment by PieceOfFall** [comment]
这是你前端的报错吧，你看后端报错

**Comment by 918975709** [comment]
![1](https://user-images.githubusercontent.com/117253763/219850980-19653c4e-ce11-40ac-9450-2cd58c4ed00f.png)

**Comment by PieceOfFall** [comment]
后端是重新开的一个cmd窗口运行的 :[后端运行](https://github.com/PieceOfFall/BookManage#%E5%90%8E%E7%AB%AF)

**Comment by PieceOfFall** [comment]
所以你这是浏览器的报错，是前端的报错信息。你是不是没启动后端

**Comment by PieceOfFall** [comment]
后端运行你要进入到后端的根目录

**Comment by 918975709** [comment]
![2](https://user-images.githubusercontent.com/117253763/219851149-509c7ddf-11d5-422e-b910-f9ceef5d6757.png)

**Comment by PieceOfFall** [comment]
你者不是后端的目录，后端在back_end文件夹下

**Comment by 918975709** [comment]
抱歉啊

**Comment by PieceOfFall** [comment]
在back_end目录下面进行后端运行的操作。没有启动后端，怎么进行业务呢

**Comment by PieceOfFall** [comment]
没事。
看得出来，你是学前端的吧

**Comment by 918975709** [comment]
![3](https://user-images.githubusercontent.com/117253763/219851255-be00a966-2d0c-4931-9b60-98043b454b23.png)
我是业余前端，

**Comment by PieceOfFall** [comment]
后端你可以学学Node.js，直接B站找Express（Node.js框架）。毕竟做前端也要知道后端怎么运行

**Comment by PieceOfFall** [comment]
这样可以了，你别叉掉，前端页面刷新一下，就可以用了

**Comment by PieceOfFall** [comment]
记得把数据库密码什么的配置一下

**Comment by 918975709** [comment]
好的，谢谢

**Comment by 918975709** [comment]
![4](https://user-images.githubusercontent.com/117253763/219851557-3ee9aeb7-1e7e-4526-a5df-04c46751731d.png)

**Comment by 918975709** [comment]
你看可以留个联系方式吗

**Comment by 918975709** [comment]
您看我还有机会吗

**Comment by PieceOfFall** [comment]
qq: 940313262，但是不一定有时间回复，最近忙毕设
