### ISSUE TITLE
管理员问题

### ISSUE THREAD

**Issue by Axslantiya** [PieceOfFall/-#2]
管理员模块好像用不了，只能登录，干不了别的事情

**Comment by PieceOfFall** [comment]
有报错信息没

**Comment by Axslantiya** [comment]
解决了，把45开头的地址改成127.0.0.1就行了 。
还有，能加个预约借书和续借的功能吗

**Comment by PieceOfFall** [comment]
这个仓库是我大二的课设了，估计不会再加新功能了。我已经快毕业了，在忙毕设

**Comment by PieceOfFall** [comment]
> 解决了，把45开头的地址改成127.0.0.1就行了 。 还有，能加个预约借书和续借的功能吗

45开头的ip是以前我租的服务器的ip，那时还不知道怎么用env生产环境和开发环境的切换，所以应该是被我漏掉了。

**Comment by PieceOfFall** [comment]
还有其它问题吗，没有的话这个issue我也关了

**Comment by Axslantiya** [comment]
哦，那我自己做吧
