### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by LGCman** [PieceOfFall/-#5]
在注册时，输入验证码后，后端cmd报错。
![QQ图片20231229001115](https://github.com/PieceOfFall/BookManage/assets/155091623/a89fb876-c160-46ae-8e43-44c99f0e352e)

**Comment by PieceOfFall** [comment]
### 请仔细查阅README文档，这是MYSQL的新版链接问题、
[https://github.com/PieceOfFall/BookManage?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98](常见问题)
### 另外，不要忘记配置邮箱授权
![353be403ee48a1fecf26ee7e9d5eb1f5](https://github.com/PieceOfFall/BookManage/assets/85009059/22bb751b-40f5-4f22-a997-25f9578730f7)
